services:
  artist-api-service:
    build:
      context: ./part2
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  book-service:
    build:
      context: ./part3
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  kong-gateway:
    image: kong:3.4
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong-config.yaml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    volumes:
      - ./part2/kong-config.yaml:/usr/local/kong/declarative/kong-config.yaml:ro
    ports:
      - "8000:8000"
      - "8001:8001"
    depends_on:
      - artist-api-service
