_format_version: "3.0"
_transform: true

services:
  - name: record-label-service
    url: http://artist-api-service:8080
    routes:
      - name: artists-route
        paths:
          - /artists
        strip_path: false
        methods:
          - GET
          - POST

    plugins:
      - name: basic-auth
        enabled: true
        config:
          hide_credentials: true

      - name: rate-limiting
        enabled: true
        config:
          minute: 5
          policy: local
          limit_by: consumer

      - name: request-size-limiting
        enabled: true
        config:
          allowed_payload_size: 1

consumers:
  - username: record-label-client

basicauth_credentials:
  - consumer: record-label-client
    username: apiuser
    password: apipassword123
